name         'camptocamp-augeas'
version      '0.0.1'
source       'https://github.com/camptocamp/puppet-apt'
dependency   'puppetlabs/stdlib', '>=3.2.0 <4.2.0'
license      'GNU GPLv3'
summary      'Camptocamp Augeas module'
description  'Augeas Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-augeas'
