name         'puppet-augeas'
version      '0.0.2'
source       'https://github.com/opentable/puppet-augeas'
dependency   'puppetlabs/stdlib', '>=3.2.0 <4.2.0'
license      'GNU GPLv3'
summary      'Opentable fork of Camptocamp Augeas module'
description  'Augeas Module for Puppet'
project_page 'https://github.com/opentable/puppet-augeas'
